### PR TITLE
Get width and length calculations correct and bigger vZ deadzone

### PR DESCRIPTION
**Pull request by ArthurAllshire**
This fixes the robot's width and length calculations.

### CODE REVIEW

**Comment by james-ward** [comment]
Seems to be some stuff in there relating to joystick deadzone?

**Comment by ArthurAllshire** [comment]
The vZ stuff is because it was too sensitive on the actual robot, but theres now a magic number in there. Let me fix that.

**Comment by james-ward** [comment]
That's fine, but put it in a seperate commit.

**Comment by james-ward** [comment]
ie amend your first commit to only be the width stuff, then make a commit for vz. You'll need to force push.

**Pull request merged**
